#ifndef _RC_Y_EXCEPTION_H
#define _RC_Y_EXCEPTION_H

#ifdef OVERFLOW
#undef OVERFLOW
#endif

namespace owca {
	enum class ExceptionCode {
		NONE=0,
		CLASS_CREATION,
		PARAM_ASSIGNED_TWICE,
		PARAM_NOT_SET,
		UNUSED_KEYWORD_PARAM,
		KEYWORD_PARAM_NOT_STRING,
		MISSING_KEY_PARAMETER,
		MISSING_VALUE_PARAMETER,
		NO_CONSTRUCTOR,
		TOO_MANY_PARAMETERS,
		NOT_ENOUGH_PARAMETERS,
		INVALID_LIST_PARAM,
		INVALID_MAP_PARAM,
		INVALID_PARAM_TYPE,
		INTEGER_OUT_OF_BOUNDS, // integer value is out of bounds for given operation (ie too large index for array access)
		UNSUPPORTED_KEYWORD_PARAMETERS,
		INVALID_VM,
		DIVISION_BY_ZERO,
		OVERFLOW,
		INVALID_IDENT,
		NOT_LVALUE,
		NOT_RVALUE,
		MISSING_MEMBER,
		TOO_MANY_ITEMS_IN_ITER,
		TOO_LITTLE_ITEMS_IN_ITER,
		INVALID_RETURN_TYPE,
		INVALID_OPERATOR_FUNCTION,
		MISSING_RETURN_VALUE,
		STACK_OVERFLOW,
		CANT_INSERT,
		KEY_NOT_FOUND,
		NO_COROUTINE_TO_STOP,
		CANT_STOP_FROM_WITHIN_USER_FUNCTION,
		CANT_RESUME_FROM_COROUTINE,
		CANT_RESUME_NORMAL_FUNCTION,
		CANT_RESUME_FINISHED_COROUTINE,
		CANT_STOP_COROUTINE_FROM_USER_FUNCTION,
		CANT_CREATE_GENERATOR_FROM_USER_FUNCTION,
		LIST_MODIFED_WHILE_BEING_SORTED,
		MAP_MODIFED_WHILE_BEING_USED,
		SET_MODIFED_WHILE_BEING_USED,
		USER=1024,
	};
	DLLEXPORT const char *ExceptionCode_text(ExceptionCode);

	class owca_exception {
		std::string _message;
	public:
		owca_exception(const std::string &txt) : _message(txt) { }

		const std::string &message() const { return _message; }
	};

}

#endif
